### ISSUE TITLE
Steps

### ISSUE THREAD

**Issue by pad1a** [tracelytics/pageguide#44]
Please give me example for 2 steps (steps_element).

**Comment by arizzitano** [comment]
@pad1a if you want to run two separate pageguides on the same page, you'll need to place the steps for each in two separate `<ul>` elements, like so:

    <ul id="first-pageguide">
        <li data-tourtarget=".your-selector-here">Here is a step description</li>
        <li data-tourtarget=".other-selector-here">Here is a step description</li>
    </ul>

    <ul id="second-pageguide">
        <li data-tourtarget=".additional-selector">Here is a step description</li>
        <li data-tourtarget=".final-selector">Here is a step description</li>
    </ul>

Then, instantiate a separate pageguide for each `<ul>`, passing the selector for each element as the `steps_element` parameter:

    var firstPageGuide = tl.pg.init({
        steps_element: '#first-pageguide'
    });
    var secondPageGuide = tl.pg.init({
        steps_element: '#second-pageguide'
    });

You'll end up with two pageguides on the page, each with its own independent set of steps. Does that answer your question?
