### ISSUE TITLE
Remove AppNeta logo from pages site

### ISSUE THREAD

**Issue by apinkham** [tracelytics/pageguide#64]
Hey @dkuebric do you mind removing the AppNeta logo from the [pageguide site]([url](http://tracelytics.github.io/pageguide/)) ? We've gotten inquiries on our appneta.com live chat about whether or not we are still maintaining it. You could also remove AppNeta from the license.

Thanks!

**Comment by dkuebric** [comment]
@apinkham sure thing--I'll put in a PR later today.

**Comment by dkuebric** [comment]
All set... "today" turned out to be about 96 hours long.  Also good to run into you yesterday @apinkham !
